 GET http://localhost:4000/cadex

###

GET http://localhost:4000/cadex?name=NiB&verb=boit

###

POST http://localhost:4000/cadex
Content-Type: application/json

{
  "name": "Mick",
  "complement": "un verre d'eau"
}

###

GET http://localhost:4000

###
GET http://localhost:4000/cadex/machin
